name: Release
on:
  release:
    types: [edited, published]
    branches:
      - main
      - feature-*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Write secrets.env
        env:
          SECRETS: ${{ secrets.SECRETS_ENV }}
          PIFILE: btcpi.Pifile
        run: |
          echo $SECRETS > $(dirname $PIFILE)/secrets.env
      - name: Build image
        uses: Nature40/pimod@v0.6.0
        with:
          pifile: btcpi.Pifile
      - name: Make tarball
        run: |
          tar -czvf btcpi.tar.gz btcpi.img
      - name: Publish binaries
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'btcpi.tar.gz'
